spring:
  application.name: core

  config.import: optional:configserver:http://localhost:8888

  datasource:
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath*:db/changelog/master.xml

server:
  servlet:
    context-path: /core

app:
  integrations:
    topics:
      profiles:
        name: profile
  object-storage:
    connection-url: ${MINIO_BASE_URL}
    cdn-base-url: ${MINIO_BASE_URL}
    user: ${MINIO_USER}
    password: ${MINIO_PASSWORD}
    photo-bucket: profile-albums
    profile-photo-folder: profiles
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    client-id: PAGANBLACKER
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        auto.register.schemas: false
        use.latest.version: true
        schema.reflection: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      group-id: cg-core.test
      properties:
        schema.registry.url: ${SCHEMA_REGISTRY_URL}
        auto.reset.offset: earliest
        enable.auto.commit: false
