spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: app_core
    password: core_password

  jpa:
    show-sql: true

  elasticsearch:
    uris: http://localhost:9200

app:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      properties:
        schema.registry.url: http://localhost:8081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        auto.register.schemas: false
        use.latest.version: true
        schema.reflection: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      group-id: cg-core.0002
      properties:
        schema.registry.url: http://localhost:8081
        auto.reset.offset: earliest
        enable.auto.commit: false
  images:
    fs-base-uri: ${PWD}/photo
    cdn-base-uri: http://localhost:9000/view

logging:
  level:
    tracer: trace
