services:
  postgres:
    container_name: postgres-prototype
    image: postgres:17.4-alpine3.21
    ports:
      - 5432:5432
    volumes:
      - /data/prototype/core:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${CORE_PG_USER}
      POSTGRES_USER: ${CORE_PG_PASSWORD}
      POSTGRES_PASSWORD: ${CORE_PG_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: ${CORE_PG_AUTH_METHOD}
