services:
  postgres:
    container_name: postgres-prototype
    image: postgres:17.4-alpine3.21
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${CORE_PG_USER}
      POSTGRES_USER: ${CORE_PG_PASSWORD}
      POSTGRES_PASSWORD: ${CORE_PG_DATABASE}
      POSTGRES_HOST_AUTH_METHOD: ${CORE_PG_AUTH_METHOD}

  elasticsearch:
    image: elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - http.cors.allow-origin=http://localhost:8085
      - http.cors.enabled=true
      - http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      - http.cors.allow-credentials=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elastic

  kibana:
    image: kibana:8.17.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  elasticvue:
    image: cars10/elasticvue
    container_name: elasticvue
    volumes:
      - "/config.json:$pwd/etc/docker/elasticvue_conf.json"
    ports:
      - "8085:8080"
    networks:
      - elastic

volumes:
  elastic_data:
    driver: local
  postgres_data:
    driver: local

networks:
  elastic:
    driver: bridge

