-- create regions table
create table regions
(
    id   varchar(2)   not null,
    name varchar(100) not null unique,
    constraint region_pk primary key (id),
    constraint region_name_unique unique (name)
);

-- create countries table
create table countries
(
    id        varchar(2)   not null,
    name      varchar(100) not null,
    region_id varchar(2)   not null references regions (id),
    constraint country_pk primary key (id),
    constraint country_name_unique unique (name),
    constraint country_to_region_fk foreign key (region_id) references regions (id)
);

-- Insert global regions
insert into regions (id, name)
values ('AF', 'Africa'),
       ('AM', 'Americas'),
       ('AS', 'Asia'),
       ('EU', 'Europe'),
       ('OC', 'Oceania');

-- Insert all countries with region associations
insert into countries (id, name, region_id)
values
    -- Africa (1)
    ('DZ', 'Algeria', 'AF'),
    ('AO', 'Angola', 'AF'),
    ('BJ', 'Benin', 'AF'),
    ('BW', 'Botswana', 'AF'),
    ('BF', 'Burkina Faso', 'AF'),
    ('BI', 'Burundi', 'AF'),
    ('CV', 'Cabo Verde', 'AF'),
    ('CM', 'Cameroon', 'AF'),
    ('CF', 'Central African Republic', 'AF'),
    ('TD', 'Chad', 'AF'),
    ('KM', 'Comoros', 'AF'),
    ('CG', 'Congo', 'AF'),
    ('CI', 'Côte d''Ivoire', 'AF'),
    ('CD', 'Democratic Republic of the Congo', 'AF'),
    ('DJ', 'Djibouti', 'AF'),
    ('EG', 'Egypt', 'AF'),
    ('GQ', 'Equatorial Guinea', 'AF'),
    ('ER', 'Eritrea', 'AF'),
    ('SZ', 'Eswatini', 'AF'),
    ('ET', 'Ethiopia', 'AF'),
    ('GA', 'Gabon', 'AF'),
    ('GM', 'Gambia', 'AF'),
    ('GH', 'Ghana', 'AF'),
    ('GN', 'Guinea', 'AF'),
    ('GW', 'Guinea-Bissau', 'AF'),
    ('KE', 'Kenya', 'AF'),
    ('LS', 'Lesotho', 'AF'),
    ('LR', 'Liberia', 'AF'),
    ('LY', 'Libya', 'AF'),
    ('MG', 'Madagascar', 'AF'),
    ('MW', 'Malawi', 'AF'),
    ('ML', 'Mali', 'AF'),
    ('MR', 'Mauritania', 'AF'),
    ('MU', 'Mauritius', 'AF'),
    ('MA', 'Morocco', 'AF'),
    ('MZ', 'Mozambique', 'AF'),
    ('NA', 'Namibia', 'AF'),
    ('NE', 'Niger', 'AF'),
    ('NG', 'Nigeria', 'AF'),
    ('RW', 'Rwanda', 'AF'),
    ('ST', 'São Tomé and Príncipe', 'AF'),
    ('SN', 'Senegal', 'AF'),
    ('SC', 'Seychelles', 'AF'),
    ('SL', 'Sierra Leone', 'AF'),
    ('SO', 'Somalia', 'AF'),
    ('ZA', 'South Africa', 'AF'),
    ('SS', 'South Sudan', 'AF'),
    ('SD', 'Sudan', 'AF'),
    ('TZ', 'Tanzania', 'AF'),
    ('TG', 'Togo', 'AF'),
    ('TN', 'Tunisia', 'AF'),
    ('UG', 'Uganda', 'AF'),
    ('ZM', 'Zambia', 'AF'),
    ('ZW', 'Zimbabwe', 'AF'),

    -- Americas (2)
    ('AG', 'Antigua and Barbuda', 'AM'),
    ('AR', 'Argentina', 'AM'),
    ('BS', 'Bahamas', 'AM'),
    ('BB', 'Barbados', 'AM'),
    ('BZ', 'Belize', 'AM'),
    ('BO', 'Bolivia', 'AM'),
    ('BR', 'Brazil', 'AM'),
    ('CA', 'Canada', 'AM'),
    ('CL', 'Chile', 'AM'),
    ('CO', 'Colombia', 'AM'),
    ('CR', 'Costa Rica', 'AM'),
    ('CU', 'Cuba', 'AM'),
    ('DM', 'Dominica', 'AM'),
    ('DO', 'Dominican Republic', 'AM'),
    ('EC', 'Ecuador', 'AM'),
    ('SV', 'El Salvador', 'AM'),
    ('GD', 'Grenada', 'AM'),
    ('GT', 'Guatemala', 'AM'),
    ('GY', 'Guyana', 'AM'),
    ('HT', 'Haiti', 'AM'),
    ('HN', 'Honduras', 'AM'),
    ('JM', 'Jamaica', 'AM'),
    ('MX', 'Mexico', 'AM'),
    ('NI', 'Nicaragua', 'AM'),
    ('PA', 'Panama', 'AM'),
    ('PY', 'Paraguay', 'AM'),
    ('PE', 'Peru', 'AM'),
    ('KN', 'Saint Kitts and Nevis', 'AM'),
    ('LC', 'Saint Lucia', 'AM'),
    ('VC', 'Saint Vincent and the Grenadines', 'AM'),
    ('SR', 'Suriname', 'AM'),
    ('TT', 'Trinidad and Tobago', 'AM'),
    ('US', 'United States', 'AM'),
    ('UY', 'Uruguay', 'AM'),
    ('VE', 'Venezuela', 'AM'),

    -- Asia (3)
    ('AF', 'Afghanistan', 'AS'),
    ('AM', 'Armenia', 'AS'),
    ('AZ', 'Azerbaijan', 'AS'),
    ('BH', 'Bahrain', 'AS'),
    ('BD', 'Bangladesh', 'AS'),
    ('BT', 'Bhutan', 'AS'),
    ('BN', 'Brunei', 'AS'),
    ('KH', 'Cambodia', 'AS'),
    ('CN', 'China', 'AS'),
    ('CY', 'Cyprus', 'AS'),
    ('GE', 'Georgia', 'AS'),
    ('IN', 'India', 'AS'),
    ('ID', 'Indonesia', 'AS'),
    ('IR', 'Iran', 'AS'),
    ('IQ', 'Iraq', 'AS'),
    ('IL', 'Israel', 'AS'),
    ('JP', 'Japan', 'AS'),
    ('JO', 'Jordan', 'AS'),
    ('KZ', 'Kazakhstan', 'AS'),
    ('KW', 'Kuwait', 'AS'),
    ('KG', 'Kyrgyzstan', 'AS'),
    ('LA', 'Laos', 'AS'),
    ('LB', 'Lebanon', 'AS'),
    ('MY', 'Malaysia', 'AS'),
    ('MV', 'Maldives', 'AS'),
    ('MN', 'Mongolia', 'AS'),
    ('MM', 'Myanmar', 'AS'),
    ('NP', 'Nepal', 'AS'),
    ('KP', 'North Korea', 'AS'),
    ('OM', 'Oman', 'AS'),
    ('PK', 'Pakistan', 'AS'),
    ('PS', 'Palestine', 'AS'),
    ('PH', 'Philippines', 'AS'),
    ('QA', 'Qatar', 'AS'),
    ('RU', 'Russia', 'AS'),
    ('SA', 'Saudi Arabia', 'AS'),
    ('SG', 'Singapore', 'AS'),
    ('KR', 'South Korea', 'AS'),
    ('LK', 'Sri Lanka', 'AS'),
    ('SY', 'Syria', 'AS'),
    ('TJ', 'Tajikistan', 'AS'),
    ('TH', 'Thailand', 'AS'),
    ('TL', 'Timor-Leste', 'AS'),
    ('TR', 'Turkey', 'AS'),
    ('TM', 'Turkmenistan', 'AS'),
    ('AE', 'United Arab Emirates', 'AS'),
    ('UZ', 'Uzbekistan', 'AS'),
    ('VN', 'Vietnam', 'AS'),
    ('YE', 'Yemen', 'AS'),

    -- Europe (4)
    ('AL', 'Albania', 'EU'),
    ('AD', 'Andorra', 'EU'),
    ('AT', 'Austria', 'EU'),
    ('BY', 'Belarus', 'EU'),
    ('BE', 'Belgium', 'EU'),
    ('BA', 'Bosnia and Herzegovina', 'EU'),
    ('BG', 'Bulgaria', 'EU'),
    ('HR', 'Croatia', 'EU'),
    ('CZ', 'Czech Republic', 'EU'),
    ('DK', 'Denmark', 'EU'),
    ('EE', 'Estonia', 'EU'),
    ('FI', 'Finland', 'EU'),
    ('FR', 'France', 'EU'),
    ('DE', 'Germany', 'EU'),
    ('GR', 'Greece', 'EU'),
    ('HU', 'Hungary', 'EU'),
    ('IS', 'Iceland', 'EU'),
    ('IE', 'Ireland', 'EU'),
    ('IT', 'Italy', 'EU'),
    ('XK', 'Kosovo', 'EU'),
    ('LV', 'Latvia', 'EU'),
    ('LI', 'Liechtenstein', 'EU'),
    ('LT', 'Lithuania', 'EU'),
    ('LU', 'Luxembourg', 'EU'),
    ('MT', 'Malta', 'EU'),
    ('MD', 'Moldova', 'EU'),
    ('MC', 'Monaco', 'EU'),
    ('ME', 'Montenegro', 'EU'),
    ('NL', 'Netherlands', 'EU'),
    ('MK', 'North Macedonia', 'EU'),
    ('NO', 'Norway', 'EU'),
    ('PL', 'Poland', 'EU'),
    ('PT', 'Portugal', 'EU'),
    ('RO', 'Romania', 'EU'),
    ('SM', 'San Marino', 'EU'),
    ('RS', 'Serbia', 'EU'),
    ('SK', 'Slovakia', 'EU'),
    ('SI', 'Slovenia', 'EU'),
    ('ES', 'Spain', 'EU'),
    ('SE', 'Sweden', 'EU'),
    ('CH', 'Switzerland', 'EU'),
    ('UA', 'Ukraine', 'EU'),
    ('GB', 'United Kingdom', 'EU'),
    ('VA', 'Vatican City', 'EU'),

    -- Oceania (5)
    ('AU', 'Australia', 'OC'),
    ('FJ', 'Fiji', 'OC'),
    ('KI', 'Kiribati', 'OC'),
    ('MH', 'Marshall Islands', 'OC'),
    ('FM', 'Micronesia', 'OC'),
    ('NR', 'Nauru', 'OC'),
    ('NZ', 'New Zealand', 'OC'),
    ('PW', 'Palau', 'OC'),
    ('PG', 'Papua New Guinea', 'OC'),
    ('WS', 'Samoa', 'OC'),
    ('SB', 'Solomon Islands', 'OC'),
    ('TO', 'Tonga', 'OC'),
    ('TV', 'Tuvalu', 'OC'),
    ('VU', 'Vanuatu', 'OC');
