spring:
  application:
    name: eureka-service-registry-server
  config.import: optional:configserver:http://localhost:8888

server:
  port: 9761

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME}
  server:
    enable-self-preservation: ${EUREKA_SERVER_ENABLE_SELF_PRESERVATION:true}
    eviction-interval-timer-in-ms: ${EUREKA_SERVER_EVICTION_INTERVAL_TIMER_IN_MS:10000}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
