server:
  port: 1111

spring:
  application.name: spring-boot-admin
  config.import: optional:configserver:http://localhost:8888
  boot:
    admin:
      client:
        url: ${SBA_ADMIN_CLIENT_URL}
      ui:
        available-languages:
          - en
          - ru
