spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    show-sql: true

  elasticsearch:
    uris: http://localhost:9200

  kafka:
    bootstrap-servers: localhost:9092

app:
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#      value-serializer: com.github.thake.kafka.avro4k.serializer.KafkaAvro4kSerializer
      properties:
        schema.registry.url: http://localhost:8081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        auto.register.schemas: false
        use.latest.version: true
        schema.reflection: true
logging:
  level:
    tracer: trace
