spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}

  jpa:
    show-sql: true

  elasticsearch:
    uris: http://localhost:9200

logging:
  level:
    tracer: trace
