server:
  port: 8082

spring:
  cassandra:
    contact-points: localhost:9042,localhost:9043,localhost:9044
    keyspace-name: chat
    local-datacenter: prototype-dc1

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.messaging.simp: DEBUG

app:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      properties:
        schema.registry.url: http://localhost:8081
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        auto.register.schemas: false
        use.latest.version: false
        schema.reflection: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        auto.reset.offset: earliest
        enable.auto.commit: false
