spring:
  application.name: chat

  config.import: optional:configserver:http://localhost:8888

  cloud.config.fail-fast: true

app:
  instance-id: chat_app_${random.uuid}
  integrations:
    topics:
      p2p-message:
        name: p2p-message

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.LongSerializer
      properties:
        schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
        auto.register.schemas: false
        use.latest.version: false
        schema.reflection: true
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.LongDeserializer
      value-deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
      properties:
        schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
        auto.reset.offset: earliest
        enable.auto.commit: false
