spring:
  cassandra:
    contact-points: localhost:9042,localhost:9043,localhost:9044
    keyspace-name: chat
    local-datacenter: prototype-dc1

app:
  instance-id: chat_app_${random.uuid}
  integrations:
    topics:
      p2p-message:
        name: p2p-message
